### PR TITLE
REST query and form parameters

### PR DESCRIPTION
**Pull request by mkrebs81**
- Separates query parameters from request path
- separate requestForm data structure when using form data instead of body
- adapted existing EIDs

### CODE REVIEW

**Comment by ergo-furrer** [comment]
@mkrebs81 I think we should leave the URL for the Clemap as it was and not add the `requestQuery` element.
So I it remains: 
```xml
  <requestMethod>GET</requestMethod>
                  <requestPath>/digitaltwins?sensor_id={{sensor_id}}</requestPath>
                  <responseQuery>
                    <queryType>JMESPathExpression</queryType>
                    <query>sum([[0].ten_sec.p_l1,[0].ten_sec.p_l2,[0].ten_sec.p_l3])</query>
                  </responseQuery>
````

Sorry that I did not see that while merging before pushing the BearerToken/Content-Type fix.
Can I revert to the Clemap EI to the status above?

**Comment by mkrebs81** [comment]
@ergo-furrer if you like, revert them.
note that the path should be `/digitaltwins/?sensor_id={{sensor_id}}` (i fixed that in my latest commit)

**Comment by ergo-furrer** [comment]
Hmm your latest commit seems to be:

```xml
                  <requestPath>/digitaltwins/</requestPath>
                  <requestQuery>
                    <parameter>
                      <name>sensor_id</name>
                      <value>{{sensor_id}}</value>
                    </parameter>
                  </requestQuery>
```
Still contains the `<requestQuery>`

**Comment by ergo-furrer** [comment]
@mkrebs81 Regarding `/digitaltwins/?sensor_id={{sensor_id}}` and `/digitaltwins?sensor_id={{sensor_id}}` i think the version without / before the ? is correct:

"When specifying query parameters in a URL, you should not include a forward slash ("/") before the question mark ("?"). The question mark separates the base URL from the query string."

**Comment by ergo-furrer** [comment]
> @mkrebs81 Regarding `/digitaltwins/?sensor_id={{sensor_id}}` and `/digitaltwins?sensor_id={{sensor_id}}` i think the version without / before the ? is correct:
> 
> "When specifying query parameters in a URL, you should not include a forward slash ("/") before the question mark ("?"). The question mark separates the base URL from the query string."

I am preparing the corrections regarding this.

**Comment by mkrebs81** [comment]
@ergo-furrer I agree, usually the path should not include the trailing slash.

However, I have no idea if CLEMAP requires the slash or not.
All existing EIDs and the CLEMAP API Python mock some students made last year have had the trailing slash so far.

**Comment by ergo-furrer** [comment]
> @ergo-furrer I agree, usually the path should not include the trailing slash.
> 
> However, I have no idea if CLEMAP requires the slash or not. All existing EIDs and the CLEMAP API Python mock some students made last year have had the trailing slash so far.

Surprisingly Clemap accepts both versions 😄 !

**Review by ergo-furrer — APPROVED** [review]

**Review by ArndGerns — APPROVED** [review]
XLS needs to be adapted as well.
I'll do that as I'm working on it anyway.

**Pull request merged**
