### PR TITLE
#295 Add mapping for value for RestAPI

### PR DESCRIPTION
**Pull request by ArndGerns**
Added mapping for value for RestAPI

It is now possible to have a mapping for read and write for a rest api datapoint.

Example:
```
<valueMapping>
  <mapping>
    <from>off</from>
    <to>false</to>
  </mapping>
  <mapping>
    <from>on</from>
    <to>true</to>
  </mapping>
</valueMapping>
```

For a write data call, the generic value is mapped with the mapping and the mapped value is written to the rest api.

For a read data call, the value is read from the rest api and then mapped to the generic value.

### CODE REVIEW

**Review by ergo-furrer — APPROVED** [review]

**Comment by ergo-furrer** [comment]
@ArndGerns @mkrebs81 : OK, for me.

**Comment by mkrebs81** [comment]
I believe this will be sufficient.

The REST API query string or parameters are strings anyway.
And the "from" content should be parsable according to the data point's data type.

I suppose the conversion direction depends on whether it is a read or write operation:
- read --> from = value returned by REST call, to = value returned to communicator
- write --> from = value given by communicator, to = value given to REST call

**Comment by ergo-furrer** [comment]
> I believe this will be sufficient.
> 
> The REST API query string or parameters are strings anyway. And the "from" content should be parsable according to the data point's data type.
> 
> I suppose the conversion direction depends on whether it is a read or write operation:
> 
> * read --> from = value returned by REST call, to = value returned to communicator
> * write --> from = value given by communicator, to = value given to REST call

It's my understanding too.

**Comment by ArndGerns** [comment]
Then it seems to be ambiguous. I guess @ergo-furrer has understood it differently.

Can we rename the mapping values in

- <restValue> => the value in the rest API call
- <jsonValue> => the value in the generic inferface

What do you think? Better names?

**Comment by ergo-furrer** [comment]
> Then it seems to be ambiguous. I guess @ergo-furrer has understood it differently.
> 
> Can we rename the mapping values in
> 
> * `<restValue>` => the value in the rest API call
> * `<jsonValue>` => the value in the generic inferface
> 
> That would be unambiguous. What do you think? Better names?

What about `<genericValue>`,  `<deviceValue>`  ?

**Comment by ArndGerns** [comment]
> > Then it seems to be ambiguous. I guess @ergo-furrer has understood it differently.
> > Can we rename the mapping values in
> > 
> > * `<restValue>` => the value in the rest API call
> > * `<jsonValue>` => the value in the generic inferface
> > 
> > That would be unambiguous. What do you think? Better names?
> 
> What about `<genericValue>`, `<deviceValue>` ?

Yes. Better.

**Comment by ArndGerns** [comment]
Have changed it now to `<genericValue>`, `<deviceValue>`.
If it is ok, I'ld merge it.

**Review by ergo-furrer — APPROVED** [review]

**Pull request merged**
